kind: Service
apiVersion: v1
metadata:
  name: jobmanager-webui
  namespace: latreider
spec:
  selector:
    component: jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  externalIPs:
    - 192.168.2.121  
